name: "Dokku Flutter Web"
description: "Deploy Flutter Web app to Dokku"
author: "Abdelrahman Shehata"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  app-name:
    description: "The name of the Dokku app"
    required: true
  web-dir:
    description: "The directory containing the web files to deploy starting from the root of the project"
    required: false
    default: "build/web"
  dokku-host:
    description: "The Dokku server host"
    required: true
  dokku-ssh-key:
    description: "The SSH private key for Dokku"
    required: true
runs:
  using: "composite"
  steps:
  - name: Setup SSH
    run: |
      mkdir -p ~/.ssh
      echo "${{ inputs.dokku-ssh-key }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -H ${{ inputs.dokku-host }} >> ~/.ssh/known_hosts
    shell: bash

  - name: Prepare temp dir
    run: |
      mkdir -p tmp-dokku-deploy/build/web
      cp -r ${{ inputs.web-dir }}/* tmp-dokku-deploy/build/web
      cd tmp-dokku-deploy
      curl -L https://raw.githubusercontent.com/abdlrhmanshehatamoussa/dokku-flutter-web/refs/heads/main/docker-templates/basic/Dockerfile -o Dockerfile
    shell: bash

  - name: Deploy to Dokku
    run: |
      cd tmp-dokku-deploy
      git init
      git config user.name "github-actions"
      git config user.email "actions@github.com"
      git remote add dokku dokku@${{ inputs.dokku-host }}:${{ inputs.app-name }}
      git add .
      git commit -m "Deploy $GITHUB_SHA"
      git push dokku master --force
    shell: bash
